project: 
  title: "Fisheries Assessment & Data Section (FADS)"
  output-dir: ./_site

website: 
  favicon: images/logo.png
  
  navbar: 
    left: 
      - href: index.qmd
        text: "Home"
      - text: "Perspectives"
        menu: 
          - href: perspectives/data-life-cycle.qmd
            text: "Data Life Cycle"
          - href: perspectives/your-role.qmd
            text: "Your Role"
          - href: perspectives/data-domain.qmd
            text: "Data Domain"
          - href: perspectives/your-tasks.qmd
            text: "Your Tasks"
          - href: perspectives/recommended-tools.qmd
            text: "Recommended Tools"
          - href: perspectives/national-and-regional-resources.qmd
            text: "National and Regional Resources"
      - href: projects.qmd
        text: "Projects"
      - href: training-resources.qmd
        text: "Training"
      - href: about.qmd
        text: "About"
    search: true
    tools:
      - icon: translate
        href: ../fr
        text: "Francais"
  repo-url: https://github.com/dfo-pacific-science/data-stewardship-unit
  repo-actions: [edit, source, issue]
  page-footer: "This work is licensed under a [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/). Built with ðŸ’– and Quarto." 

lang: en

