project: 
  title: "l'Unit√© de gestion des donn√©es"
  output-dir: ./_site/fr

website: 
  favicon: images/logo.png
  navbar: 
    left: 
      - href: index.qmd
        text: "Accueil"
      - text: "Perspectives"
        menu: 
          - href: perspectives/data-life-cycle.qmd
            text: "Cycle de vie des donn√©es"
          - href: perspectives/your-role.qmd
            text: "Votre r√¥le"
          - href: perspectives/data-domain.qmd
            text: "Votre domaine" 
          - href: perspectives/your-tasks.qmd
            text: "Votre t√¢che"
          - href: perspectives/recommended-tools.qmd
            text: "Outils recommand√©s"
          - href: perspectives/national-and-regional-resources.qmd
            text: "Ressources nationales et r√©gionales"
      - href: training-resources.qmd
        text: "Formation"
      - href: the-team.qmd
        text: "Notre √©quipe"
      - href: about.qmd
        text: "Sur"
    search: true
    tools:
      - icon: translate
        href: ../
        text: "English"
  repo-url: https://dfo-pacific-science.github.io/data-stewardship-unit/
  repo-actions: [edit, source, issue]
  page-footer: "Cette ≈ìuvre est plac√©e sous licence [CC BY 4.0 licence] (https://creativecommons.org/licenses/by/4.0/). Construit avec üíñ et Quarto." 

lang: fr

format:
  html: 
    theme: cosmo
    toc: true
    css: styles/custom.css
    
execute:
  freeze: auto